const products = [
  {
    _id: '1',
    name: 'Maillot Équipe de France',
    image: '/images/france.jpeg',
    description:
      'Maillot domicile de l\'Équipe de France',
    brand: 'Nike',
    category: 'Maillot Domicile',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Maillot Équipe d\'Allemagne',
    image: '/images/allemagne.jpeg',
    description:
        'Maillot domicile de l\'Allemagne',
    brand: 'Nike',
    category: 'Maillot Domicile',
    price: 59.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Maillot Équipe d\'Angleterre',
    image: '/images/angleterre.jpeg',
    description:
        'Maillot domicile de l\'Angleterre',
    brand: 'Nike',
    category: 'Maillot Domicile',
    price: 59.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Maillot Équipe de Beglique',
    image: '/images/belgique.jpeg',
    description:
        'Maillot domicile de l\'Équipe de Belgique',
    brand: 'Adidas',
    category: 'Maillot Domicile',
    price: 69.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Maillot Équipe d\'Espagne',
    image: '/images/espagne.jpeg',
    description:
        'Maillot domicile de l\'Équipe d\'Espagne',
    brand: 'Nike',
    category: 'Maillot Domicile',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Maillot Équipe d\'Italie',
    image: '/images/italie.jpeg',
    description:
        'Maillot de l\'Équipe d\'Italie',
    brand: 'Puma',
    category: 'Maillot Domicile',
    price: 79.99,
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Maillot Équipe des Pays-Bas',
    image: '/images/paysbas.jpeg',
    description:
        'Maillot domicile de l\'Équipe des Pays-Bas',
    brand: 'Nike',
    category: 'Maillot Domicile',
    price: 49.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: '8',
    name: 'Maillot Équipe du Portugal',
    image: '/images/portugal.jpeg',
    description:
        'Maillot domicile de l\'Équipe du Portugal',
    brand: 'Nike',
    category: 'Maillot Domicile',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]

export default products
